### ISSUE TITLE
collision with new glibc identifier

### ISSUE THREAD

**Issue by 100espressos** [google/filament#5203]
```
filament/libs/image/src/ImageSampler.cpp:41:17: error: expected unqualified-id
constexpr float M_PIf = float(filament::math::F_PI);
                ^
/usr/include/math.h:1168:17: note: expanded from macro 'M_PIf'
# define M_PIf          3.14159265358979323846f /* pi */
```

To reproduce, compile with glibc 2.35+.

**References**

https://sourceware.org/pipermail/libc-alpha/2022-February/136040.html

```
<math.h> macros for single-precision float constants are added as a
  GNU extension: M_Ef, M_LOG2Ef, M_LOG10Ef, M_LN2f, M_LN10f, M_PIf,
  M_PI_2f, M_PI_4f, M_1_PIf, M_2_PIf, M_2_SQRTPIf, M_SQRT2f and
  M_SQRT1_2f.
```

**Desktop**
Linux

*edit: Closing as these should be caught by CI

**Comment by GokulDas027** [comment]
Having the same issue while building filament on Manjaro with `core/glibc 2.35-6 `. Have you found any workaround for this issue.

**Comment by 100espressos** [comment]
One workaround is to rename the constant (used only in one file) to something else, like `M_PI_f` in this diff:

```diff --git a/libs/image/src/ImageSampler.cpp b/libs/image/src/ImageSampler.cpp
index 98073c489..d8bc32f82 100644
--- a/libs/image/src/ImageSampler.cpp
+++ b/libs/image/src/ImageSampler.cpp
@@ -38,7 +38,7 @@ struct FilterFunction {
     bool rejectExternalSamples = true;
 };
 
-constexpr float M_PIf = float(filament::math::F_PI);
+constexpr float M_PI_f = float(filament::math::F_PI);
 
 const FilterFunction Box {
     .fn = [](float t) { return t <= 0.5f ? 1.0f : 0.0f; },
@@ -50,7 +50,7 @@ const FilterFunction Nearest { Box.fn, 0.0f };
 const FilterFunction Gaussian {
     .fn = [](float t) {
         if (t >= 2.0) return 0.0f;
-        const float scale = 1.0f / std::sqrt(0.5f * M_PIf);
+        const float scale = 1.0f / std::sqrt(0.5f * M_PI_f);
         return std::exp(-2.0f * t * t) * scale;
     },
     .boundingRadius = 2
@@ -86,7 +86,7 @@ const FilterFunction Mitchell {
 // Not bothering with a fast approximation since we cache results for each row.
 float sinc(float t) {
     if (t <= 0.00001f) return 1.0f;
-    return std::sin(M_PIf * t) / (M_PIf * t);
+    return std::sin(M_PI_f * t) / (M_PI_f * t);
 }
```

**Comment by GokulDas027** [comment]
Okay, that works for the immediate need. Thanks.
