### ISSUE TITLE
android build with 1.4.3 error: undefined reference to 'filament::Engine::streamAlloc (mac)

### ISSUE THREAD

**Issue by dilemmacc** [google/filament#1982]
filament-1.4.3/android/common/CallbackUtils.cpp:67: error: undefined reference to 'filament::Engine::streamAlloc(unsigned int, unsigned int)'

**Comment by prideout** [comment]
How did you reproduce this build error?  This method takes `size_t` which is usually not equivalent to unsigned int.
