### ISSUE TITLE
matc regression with sampler2dArray

### ISSUE THREAD

**Issue by prideout** [google/filament#3770]
To repro, add the following line to the `parameters` section of any of our sample materials (e.g. mirror.mat)

        { type : sampler2dArray, name : test },

This results in:

```
ERROR: 0:166: 'sampler/image' : type requires declaration of default precision qualifier
ERROR: 0:166: '' : compilation terminated
ERROR: 2 compilation errors.  No code generated.
```

I am not sure when this regressed but I can say that this worked on main on Jan 29.

**Comment by prideout** [comment]
This regressed with #3524 @bejado

**Comment by bejado** [comment]
Thanks, I'll take a look at it today

**Comment by bejado** [comment]
As a workaround for now, you can add `precision : high`:

```
    { type : sampler2dArray, name : test, precision : high },
```
