### ISSUE TITLE
Build fails on MacOS Big Sur 11.6.2

### ISSUE THREAD

**Issue by georgematheos** [google/filament#5044]
**Describe the bug**
A crash occurs when trying to build from source on version 1.16.0.

**To Reproduce**
Per `BUILDING.md`, I ran
```
$ mkdir out/cmake-release
$ cd out/cmake-release
$ cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../release/filament ../..
$ ninja
```
This caused an error.  I then ran `./build.sh release` and the same error occurred.

**Expected behavior**
I expected Filament to build.

**Logs**
```
georgematheos@Georges-MacBook-Pro-3 filament-1.16.0 % ./build.sh release
Building release in out/cmake-release...
[11/237] Building CXX object filament/...ackend.dir/src/metal/MetalContext.mm.o
FAILED: filament/backend/CMakeFiles/backend.dir/src/metal/MetalContext.mm.o 
/Library/Developer/CommandLineTools/usr/bin/c++ -DFILAMENT_DFG_LUT_SIZE=128 -DFILAMENT_DRIVER_SUPPORTS_VULKAN -DFILAMENT_ENABLE_MATDBG=0 -DFILAMENT_METAL_HANDLE_ARENA_SIZE_IN_MB=8 -DFILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB=1 -DFILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB=4 -DFILAMENT_PER_FRAME_COMMANDS_SIZE_IN_MB=1 -DFILAMENT_PER_RENDER_PASS_ARENA_SIZE_IN_MB=2 -DFILAMENT_SUPPORTS_METAL -DFILAMENT_SUPPORTS_OPENGL -DSYSTRACE_TAG=2 -I/Users/georgematheos/Developer/research/Filament/filament-1.16.0/filament/include -I/Users/georgematheos/Developer/research/Filament/filament-1.16.0/out/cmake-release/filament -I/Users/georgematheos/Developer/research/Filament/filament-1.16.0/filament/src -I/Users/georgematheos/Developer/research/Filament/filament-1.16.0/filament/backend/include -I/Users/georgematheos/Developer/research/Filament/filament-1.16.0/filament/backend/src -I/Users/georgematheos/Developer/research/Filament/filament-1.16.0/out/cmake-release/filament/backend -I/Users/georgematheos/Developer/research/Filament/filament-1.16.0/libs/math/include -I/Users/georgematheos/Developer/research/Filament/filament-1.16.0/libs/utils/include -I/Users/georgematheos/Developer/research/Filament/filament-1.16.0/third_party/robin-map/tnt/.. -I/Users/georgematheos/Developer/research/Filament/filament-1.16.0/libs/bluegl/include -I/Users/georgematheos/Developer/research/Filament/filament-1.16.0/libs/bluevk/include -I/Users/georgematheos/Developer/research/Filament/filament-1.16.0/third_party/vkmemalloc/tnt/../include -I/Users/georgematheos/Developer/research/Filament/filament-1.16.0/third_party/smol-v/tnt/../source -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -fcolor-diagnostics -fvisibility=hidden -O3 -DNDEBUG -fomit-frame-pointer -ffunction-sections -fdata-sections  -fno-stack-check -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.0.sdk -fobjc-arc -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wnewline-eof -Wdeprecated -Wundef -Wgnu-conditional-omitted-operand -Wweak-vtables -Wnon-virtual-dtor -Wclass-varargs -Wimplicit-fallthrough -Wover-aligned -ffast-math -ffp-contract=fast -fvisibility-inlines-hidden -fstrict-vtable-pointers -MD -MT filament/backend/CMakeFiles/backend.dir/src/metal/MetalContext.mm.o -MF filament/backend/CMakeFiles/backend.dir/src/metal/MetalContext.mm.o.d -o filament/backend/CMakeFiles/backend.dir/src/metal/MetalContext.mm.o -c /Users/georgematheos/Developer/research/Filament/filament-1.16.0/filament/backend/src/metal/MetalContext.mm
/Users/georgematheos/Developer/research/Filament/filament-1.16.0/filament/backend/src/metal/MetalContext.mm:41:36: error: use of undeclared identifier 'MTLGPUFamilyApple7'
        if ([device supportsFamily:MTLGPUFamilyApple7]) {
                                   ^
1 error generated.
[18/237] Compiling material materials/sandboxLitTh...rated/material/sandboxLitThinRefractionSsr.filamat
ninja: build stopped: subcommand failed.
```

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.6.2 (20G314)
 - GPU: Intel Iris Pro 1536 MB
 - Backend: I don't know; I just ran the build script.

**Comment by romainguy** [comment]
You probably just need to update your Xcode and associated SDKs.

@bejado to confirm

**Comment by georgematheos** [comment]
I don't have Xcode; only the command-line-tools.  When I run 
```
xcode-select --update
```
it gives me the message
```
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```
The "Software Update" pane does not show an update for the command-line-tools, only the upgrade to MacOS Monterrey.  Do I need to be on MacOS Monterrey for Filament to work?

**Comment by pixelflinger** [comment]
Filament is definitely working on 11.6.2 since this is what I'm using. 
Please move this to `discussions` instead.

**Comment by bejado** [comment]
@georgematheos No, you do not need to be on Monterey to build Filament. You're using `MacOSX11.0.sdk`, which is old. You should upgrade to the latest SDK. This is typically done by upgrading Xcode.

To check:
```
xcodebuild -sdk -version | grep MacOS
```
