### ISSUE TITLE
Vulkan/Android does not compile using NDK 21.3 or NDK 21.1 [in macOS]

### ISSUE THREAD

**Issue by alexey-pelykh** [google/filament#3200]
```
../../filament/backend/src/vulkan/VulkanHandles.cpp:204:30: error: assigning to 'VkSurfaceKHR' (aka 'unsigned long long') from incompatible type 'nullptr_t'
    surfaceContext.surface = nullptr;
                             ^~~~~~~
1 error generated.
[95/645] Building CXX object filament/backend/CMakeFiles/backend.dir/src/vulkan/VulkanDriver.cpp.o
FAILED: filament/backend/CMakeFiles/backend.dir/src/vulkan/VulkanDriver.cpp.o
/Users/opelykh/Library/Android/sdk/ndk/21.3.6528147/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi19-clang++ -DFILAMENT_DFG_LUT_SIZE=64 -DFILAMENT_DRIVER_SUPPORTS_VULKAN -DFILAMENT_ENABLE_MATDBG=0 -DFILAMENT_MIN_COMMAND_BUFFERS_SIZE_IN_MB=1 -DFILAMENT_OPENGL_HANDLE_ARENA_SIZE_IN_MB=2 -DFILAMENT_PER_FRAME_COMMANDS_SIZE_IN_MB=1 -DFILAMENT_PER_RENDER_PASS_ARENA_SIZE_IN_MB=2 -DSYSTRACE_TAG=2 -I../../filament/include -Ifilament -I../../filament/src -I../../filament/backend/include -I../../filament/backend/src -I../../libs/math/include -I../../libs/utils/include -I../../third_party/robin-map/tnt/.. -I../../libs/bluevk/include -I../../third_party/vkmemalloc/tnt/../src -mthumb -march=armv7-a -mcpu=cortex-a15 -mfloat-abi=softfp -mfpu=neon-vfpv4 -DANDROID -fPIE -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -fcolor-diagnostics -DTNT_DEV -g -fstack-protector  -fPIC -Wall -Wextra -Wno-unused-parameter -Wextra-semi -Wnewline-eof -Wdeprecated -Wundef -Wgnu-conditional-omitted-operand -Wweak-vtables -Wnon-virtual-dtor -Wclass-varargs -Wimplicit-fallthrough -Wover-aligned -MD -MT filament/backend/CMakeFiles/backend.dir/src/vulkan/VulkanDriver.cpp.o -MF filament/backend/CMakeFiles/backend.dir/src/vulkan/VulkanDriver.cpp.o.d -o filament/backend/CMakeFiles/backend.dir/src/vulkan/VulkanDriver.cpp.o -c ../../filament/backend/src/vulkan/VulkanDriver.cpp
../../filament/backend/src/vulkan/VulkanDriver.cpp:1431:32: error: cannot initialize a parameter of type 'filament::backend::VulkanDisposer::Key' (aka 'const void *') with an lvalue of type 'VkImage' (aka 'unsigned long long')
    mDisposer.createDisposable(stagingImage, [=] () {
                               ^~~~~~~~~~~~
../../filament/backend/src/vulkan/VulkanDisposer.h:41:31: note: passing argument to parameter 'resource' here
    void createDisposable(Key resource, std::function<void()> destructor) noexcept;
                              ^
../../filament/backend/src/vulkan/VulkanDriver.cpp:1477:31: error: cannot initialize a parameter of type 'filament::backend::VulkanDisposer::Key' (aka 'const void *') with an lvalue of type 'VkImage' (aka 'unsigned long long')
    mDisposer.removeReference(stagingImage);
                              ^~~~~~~~~~~~
```

**Comment by alexey-pelykh** [comment]
I've tested the build using NDK 21.1 - works, so either NDK 21.2 or 21.3 are not working
